package net.es.oscars.nsi.beans;

public enum NsiConnectionEventType {
    RESERVE_RECEIVED ("RESERVE_RECEIVED"),
    RESERVE_CONFIRM ("RESERVE_CONFIRM"),
    RESERVE_FAILED("RESERVE_FAILED"),
    RESERVE_COMMIT_RECEIVED ("RESERVE_COMMIT_RECEIVED"),
    RESERVE_COMMIT_CONFIRM ("RESERVE_COMMIT_CONFIRM"),
    RESERVE_COMMIT_FAILED("RESERVE_COMMIT_FAILED"),
    RESERVE_ABORT_RECEIVED ("RESERVE_ABORT_RECEIVED"),
    RESERVE_ABORT_CONFIRM ("RESERVE_ABORT_CONFIRM"),

    PROVISION_RECEIVED ("PROVISION_RECEIVED"),
    PROVISION_CONFIRM("PROVISION_CONFIRM"),
    PROVISION_FAILED("PROVISION_FAILED"),
    RELEASE_RECEIVED("RELEASE_RECEIVED"),
    RELEASE_CONFIRM("RELEASE_CONFIRM"),
    RELEASE_FAILED("RELEASE_FAILED"),
    TERMINATE_RECEIVED("TERMINATE_RECEIVED"),
    TERMINATE_CONFIRM("TERMINATE_CONFIRM"),
    RESERVE_TIMEOUT("RESERVE_TIMEOUT"),
    FORCED_END("FORCED_END");


    private final String code;
    NsiConnectionEventType(String code) {
        this.code = code;
    }
    public String toString() {
        return code;
    }
}
