apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oscars-backend-external-secret # Name of this object. MUST NOT match target name.
spec:
  data:
    - secretKey: NSO_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: oscars/backend
        metadataPolicy: None
        property: NSO_PASSWORD
    - secretKey: NSO_USERNAME
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: oscars/backend
        metadataPolicy: None
        property: NSO_USERNAME
  refreshInterval: 300s
  secretStoreRef:
    kind: ClusterSecretStore
    name: eso-hvault-ocdappsdev
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: oscars-backend-secrets # The secret object that gets created and used within the container