apiVersion: v1
kind: Secret
metadata:
  name: tag-categories-sites.json
type: Opaque
data:
  tag-categories-sites.json: WwogIHsKICAgICJjYXRlZ29yeSI6ICJzaXRlIiwKICAgICJkZXNjcmlwdGlvbiI6ICJDaG9vc2Ugc2l0ZShzKSIsCiAgICAiaW5wdXQiOiAiU0VMRUNUIiwKICAgICJtYW5kYXRvcnkiOiBmYWxzZSwKICAgICJtdWx0aXZhbHVlIjogdHJ1ZSwKICAgICJvcHRpb25zIjogWyJMQk5MIiwgIkZOQUwiLCAiU0xBQyIsICJQTk5MIl0KICB9Cl0=
